-- Generated by migration-tools/users-sql.ts
-- Review before running on production.
-- Each INSERT uses ON CONFLICT DO NOTHING (PostgreSQL 15+; ignores duplicate unique/PK violations).
-- auth.identities / public."user" / user_team_client: INSERT...SELECT from auth.users by email so user_id matches when auth.users insert was skipped (duplicate email).
-- App user PK column defaults to user_id; override with MIGRATION_APP_USER_ID_COLUMN in .env if needed.
-- user_team_client: table=public.user_team_client, client_id=bwa, user_role=player
-- user_team_client.user_id FK -> public."user"(<PK>), not auth.users; value = auth.users.id uuid.
-- app user: table=public."user", columns="user_id", "email", "full_name"
-- user_team_client: only id, user_id, client_id, user_role (no created_at — add via env if needed).

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at,
  email_change_token_new, email_change, email_change_sent_at, last_sign_in_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at,
  phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at,
  email_change_token_current, email_change_confirm_status, banned_until,
  reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous)
VALUES ('00000000-0000-0000-0000-000000000000'::uuid, 'dd22e22f-0c06-4414-9634-d9de12f8a7be'::uuid, 'authenticated', 'authenticated',
  'adonias.neto@bwa.global', '$2b$10$MBjyumKr.xE.qblrtjuHqO1PoOL3koJCGFuHaZRhmuadHTJM6/Eei', '2026-04-24T20:54:18.176Z'::timestamptz,
  NULL, '', NULL, '', NULL, '', '', NULL, NULL,
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"email_verified":true,"name":"ADONIAS DE MEDEIROS COSTA NETO","is_active":true}'::jsonb,
  NULL, '2026-04-24T20:54:18.176Z'::timestamptz, '2026-04-24T20:54:18.176Z'::timestamptz,
  NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false)
ON CONFLICT DO NOTHING;

INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at, id)
SELECT u.id, u.id,
  jsonb_build_object(
    'sub', u.id::text,
    'email', u.email,
    'email_verified', true,
    'phone_verified', false,
    'name', to_jsonb(trim('ADONIAS DE MEDEIROS COSTA NETO'::text))
  ),
  'email',
  '2026-04-24T20:54:18.176Z'::timestamptz,
  '2026-04-24T20:54:18.176Z'::timestamptz,
  '2026-04-24T20:54:18.176Z'::timestamptz,
  gen_random_uuid()
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adonias.neto@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO public."user" ("user_id", "email", "full_name")
SELECT u.id, u.email, trim('ADONIAS DE MEDEIROS COSTA NETO'::text)
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adonias.neto@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO public.user_team_client (id, user_id, client_id, user_role)
SELECT gen_random_uuid(), u.id, 'bwa', 'player'
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adonias.neto@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at,
  email_change_token_new, email_change, email_change_sent_at, last_sign_in_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at,
  phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at,
  email_change_token_current, email_change_confirm_status, banned_until,
  reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous)
VALUES ('00000000-0000-0000-0000-000000000000'::uuid, 'a96a9b0f-fb3b-48f9-8578-58734cb18ac3'::uuid, 'authenticated', 'authenticated',
  'adriane.meireles@bwa.global', '$2b$10$EdOxXjXaTo28Eeammn01buhl4X4KCGi2VaTTpq7em2qiDVruyKpFi', '2026-04-24T20:54:18.288Z'::timestamptz,
  NULL, '', NULL, '', NULL, '', '', NULL, NULL,
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"email_verified":true,"name":"adriane.meireles","is_active":true}'::jsonb,
  NULL, '2026-04-24T20:54:18.288Z'::timestamptz, '2026-04-24T20:54:18.288Z'::timestamptz,
  NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false)
ON CONFLICT DO NOTHING;

INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at, id)
SELECT u.id, u.id,
  jsonb_build_object(
    'sub', u.id::text,
    'email', u.email,
    'email_verified', true,
    'phone_verified', false,
    'name', to_jsonb(trim('adriane.meireles'::text))
  ),
  'email',
  '2026-04-24T20:54:18.288Z'::timestamptz,
  '2026-04-24T20:54:18.288Z'::timestamptz,
  '2026-04-24T20:54:18.288Z'::timestamptz,
  gen_random_uuid()
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adriane.meireles@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO public."user" ("user_id", "email", "full_name")
SELECT u.id, u.email, trim('adriane.meireles'::text)
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adriane.meireles@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO public.user_team_client (id, user_id, client_id, user_role)
SELECT gen_random_uuid(), u.id, 'bwa', 'player'
FROM auth.users u
WHERE lower(trim(u.email)) = lower(trim('adriane.meireles@bwa.global'))
LIMIT 1
ON CONFLICT DO NOTHING;
