import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import * as bcrypt from 'bcryptjs';
import { loadRepoEnv, envStr } from './loadEnv';

type UserRow = {
  email: string;
  plainPassword: string;
  passwordFromCsv?: boolean;
  /** Display name (from CSV Nome, Funifier extra, or email local-part). */
  fullName?: string;
};

const DEFAULT_COST = 10;

function parseArgs(argv: string[]): {
  input: string;
  out: string;
  help: boolean;
} {
  let input = path.resolve(__dirname, '..', 'output', 'users-with-passwords.json');
  let out = path.resolve(__dirname, '..', 'output', 'users-insert.sql');
  let help = false;
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') {
      help = true;
    } else if (a === '--in' && argv[i + 1]) {
      input = path.resolve(argv[++i]);
    } else if (a === '--out' && argv[i + 1]) {
      out = path.resolve(argv[++i]);
    }
  }
  return { input, out, help };
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

/** Double-quote a PostgreSQL identifier (handles reserved words and mixed case). */
function sqlIdent(s: string): string {
  const t = s.trim();
  return `"${t.replace(/"/g, '""')}"`;
}

function main(): void {
  loadRepoEnv();
  const args = parseArgs(process.argv);
  if (args.help) {
    console.log(`Usage: npm run users:sql -- --in <users.json> --out <file.sql>
Reads JSON array { email, plainPassword, fullName? }[] from users-export.
Env (optional):
  USER_TEAM_CLIENT_TABLE (default public.user_team_client)
  MIGRATION_CLIENT_ID (default bwa), MIGRATION_USER_ROLE (default player)
  MIGRATION_APP_USER_TABLE (default public."user") — app user row; FK user_team_client.user_id -> that PK
  MIGRATION_APP_USER_ID_COLUMN (default user_id) — PK column on "user"
  MIGRATION_APP_USER_EMAIL_COLUMN (default email)
  MIGRATION_APP_USER_NAME_COLUMN (default full_name) — set to - to omit
  MIGRATION_SKIP_APP_USER_INSERT=true — omit app user INSERT (only if you fill "user" elsewhere)`);
    process.exit(0);
  }

  if (!fs.existsSync(args.input)) {
    console.error('Input not found:', args.input);
    process.exit(1);
  }

  const rows = JSON.parse(fs.readFileSync(args.input, 'utf8')) as UserRow[];
  if (!Array.isArray(rows)) {
    console.error('Expected JSON array');
    process.exit(1);
  }

  const teamClientTable =
    envStr('USER_TEAM_CLIENT_TABLE', 'user_team_client_table') || 'public.user_team_client';
  const migrationClientId = envStr('MIGRATION_CLIENT_ID', 'migration_client_id') || 'bwa';
  const migrationUserRole = envStr('MIGRATION_USER_ROLE', 'migration_user_role') || 'player';
  const appUserTable =
    envStr('MIGRATION_APP_USER_TABLE', 'migration_app_user_table') || 'public."user"';
  const appUserIdCol =
    envStr('MIGRATION_APP_USER_ID_COLUMN', 'migration_app_user_id_column').trim() || 'user_id';
  const appUserEmailCol =
    envStr('MIGRATION_APP_USER_EMAIL_COLUMN', 'migration_app_user_email_column').trim() ||
    'email';
  const appUserNameColRaw = envStr(
    'MIGRATION_APP_USER_NAME_COLUMN',
    'migration_app_user_name_column'
  ).trim();
  /** Omit display-name column when env is exactly "-". Otherwise default column is `full_name`. */
  const appUserNameCol = appUserNameColRaw === '-' ? '' : appUserNameColRaw || 'full_name';
  const skipAppUser =
    envStr('MIGRATION_SKIP_APP_USER_INSERT', 'migration_skip_app_user_insert').toLowerCase() ===
    'true';

  const chunks: string[] = [];
  chunks.push('-- Generated by migration-tools/users-sql.ts');
  chunks.push('-- Review before running on production.');
  chunks.push(
    '-- Each INSERT uses ON CONFLICT DO NOTHING (PostgreSQL 15+; ignores duplicate unique/PK violations).'
  );
  chunks.push(
    '-- auth.identities / public."user" / user_team_client: INSERT...SELECT from auth.users by email so user_id matches when auth.users insert was skipped (duplicate email).'
  );
  chunks.push(
    '-- App user PK column defaults to user_id; override with MIGRATION_APP_USER_ID_COLUMN in .env if needed.'
  );
  chunks.push(
    `-- user_team_client: table=${teamClientTable}, client_id=${migrationClientId}, user_role=${migrationUserRole}`
  );
  chunks.push(
    '-- user_team_client.user_id FK -> public."user"(<PK>), not auth.users; value = auth.users.id uuid.'
  );
  const appUserColsDesc = skipAppUser
    ? '(SKIPPED)'
    : [sqlIdent(appUserIdCol), sqlIdent(appUserEmailCol), appUserNameCol ? sqlIdent(appUserNameCol) : null]
        .filter(Boolean)
        .join(', ');
  chunks.push(`-- app user: table=${appUserTable}, columns=${appUserColsDesc}`);
  chunks.push(
    '-- user_team_client: only id, user_id, client_id, user_role (no created_at — add via env if needed).\n'
  );

  for (const row of rows) {
    const email = String(row.email).trim().toLowerCase();
    if (!email) {
      continue;
    }
    const displayName =
      (row.fullName && String(row.fullName).trim()) || email.split('@')[0] || email;
    const plain = String(row.plainPassword ?? '123456');
    const salt = bcrypt.genSaltSync(DEFAULT_COST);
    const hashedPassword = bcrypt.hashSync(plain, salt);
    const userId = crypto.randomUUID();
    const now = new Date().toISOString();
    const emailMatch = `lower(trim(u.email)) = lower(trim('${sqlEscape(email)}'))`;

    const rawUserMeta = JSON.stringify({
      email_verified: true,
      name: displayName,
      is_active: true
    });

    chunks.push(`INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at,
  email_change_token_new, email_change, email_change_sent_at, last_sign_in_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at,
  phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at,
  email_change_token_current, email_change_confirm_status, banned_until,
  reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous)
VALUES ('00000000-0000-0000-0000-000000000000'::uuid, '${userId}'::uuid, 'authenticated', 'authenticated',
  '${sqlEscape(email)}', '${sqlEscape(hashedPassword)}', '${now}'::timestamptz,
  NULL, '', NULL, '', NULL, '', '', NULL, NULL,
  '{"provider":"email","providers":["email"]}'::jsonb,
  '${sqlEscape(rawUserMeta)}'::jsonb,
  NULL, '${now}'::timestamptz, '${now}'::timestamptz,
  NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false)
ON CONFLICT DO NOTHING;\n`);

    chunks.push(`INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at, id)
SELECT u.id, u.id,
  jsonb_build_object(
    'sub', u.id::text,
    'email', u.email,
    'email_verified', true,
    'phone_verified', false,
    'name', to_jsonb(trim('${sqlEscape(displayName)}'::text))
  ),
  'email',
  '${now}'::timestamptz,
  '${now}'::timestamptz,
  '${now}'::timestamptz,
  gen_random_uuid()
FROM auth.users u
WHERE ${emailMatch}
LIMIT 1
ON CONFLICT DO NOTHING;\n`);

    if (!skipAppUser) {
      const cols = [sqlIdent(appUserIdCol), sqlIdent(appUserEmailCol)];
      const selCols = [`u.id`, `u.email`];
      if (appUserNameCol) {
        cols.push(sqlIdent(appUserNameCol));
        selCols.push(`trim('${sqlEscape(displayName)}'::text)`);
      }
      chunks.push(`INSERT INTO ${appUserTable} (${cols.join(', ')})
SELECT ${selCols.join(', ')}
FROM auth.users u
WHERE ${emailMatch}
LIMIT 1
ON CONFLICT DO NOTHING;\n`);
    }

    chunks.push(`INSERT INTO ${teamClientTable} (id, user_id, client_id, user_role)
SELECT gen_random_uuid(), u.id, '${sqlEscape(migrationClientId)}', '${sqlEscape(migrationUserRole)}'
FROM auth.users u
WHERE ${emailMatch}
LIMIT 1
ON CONFLICT DO NOTHING;\n`);
  }

  fs.mkdirSync(path.dirname(args.out), { recursive: true });
  fs.writeFileSync(args.out, chunks.join('\n'), 'utf8');
  const n = rows.filter(r => String(r.email).trim()).length;
  const parts = ['auth.users', 'auth.identities'];
  if (!skipAppUser) {
    parts.push('app "user"');
  }
  parts.push('user_team_client');
  console.log('Wrote', args.out, 'users:', n, '(per user: ' + parts.join(' + ') + ')');
}

main();
